name: hafeZ
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython >=1.78
  - blast >=2.10
  - pyhmmer >=0.10.0
  - matplotlib-base >=3.3.4
  - minimap2 >=2.18
  - mosdepth >=0.3.1
  - numpy >=1.20.1
  - pandas >=1.2.4
  - pyrodigal >=3.0.0
  - pysam >=0.16.0.1
  - samtools >=1.11
  - scipy >=1.6.2
  - seaborn >0.11.1
  - rasusa >=0.7.0



